'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useToast } from '@/contexts/ToastContext';
import { Package, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function AddProductPage() {
  const router = useRouter();
  const toast = useToast();
  const [loading, setLoading] = useState(false);
  
  const [formData, setFormData] = useState({
    id: '',
    slug: '',
    name: '',
    category: 'books',
    price: '',
    stock: '100',
    description: '',
    image: '',
    bundleTitle: '',
    booksIncluded: '1',
    badge: ''
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    if (name === 'slug') {
      const cleanSlug = value
        .toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^a-z0-9-]/g, '')
        .replace(/-+/g, '-');
      setFormData(prev => ({ ...prev, slug: cleanSlug }));
    } else {
      setFormData(prev => {
        const next = { ...prev, [name]: value };
        if (name === 'name') {
          next.slug = value
            .toLowerCase()
            .replace(/\s+/g, '-')
            .replace(/[^a-z0-9-]/g, '')
            .replace(/-+/g, '-');
        }
        return next;
      });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const payload = {
        ...formData,
        price: parseFloat(formData.price),
        stock: parseInt(formData.stock),
        booksIncluded: parseInt(formData.booksIncluded)
      };

      const res = await fetch('/api/admin/products', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      
      if (res.ok) {
        toast.success('Product added successfully');
        router.push('/admin/products');
      } else {
        const error = await res.json();
        toast.error(error.error || 'Failed to add product');
      }
    } catch (err) {
      toast.error('Failed to add product');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl">
      {/* Page Header */}
      <div className="admin-page-header">
        <div className="flex items-center gap-3">
          <Link href="/admin/products" className="btn btn-ghost btn-sm btn-icon" title="Go Back">
            <ArrowLeft size={20} />
          </Link>
          <div>
            <h2 className="admin-page-title">
              <Package size={24} />
              Add New Product
            </h2>
            <p className="admin-page-desc">Create a new catalog item or study material bundle</p>
          </div>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="admin-card space-y-8">
        
        {/* Section 1: Basic Info */}
        <div className="admin-form-section">
          <h3 className="admin-form-section__title">Basic Catalog Information</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            <div className="form-group">
              <label className="form-label">Product ID (e.g., p1, m2)</label>
              <input required name="id" value={formData.id} onChange={handleChange} placeholder="e.g. p1" className="form-input" />
            </div>

            <div className="form-group">
              <label className="form-label">URL Slug (autogenerated)</label>
              <input required name="slug" value={formData.slug} onChange={handleChange} placeholder="e.g. study-pack-pa" className="form-input" />
            </div>

            <div className="form-group sm:col-span-2">
              <label className="form-label">Product Title / Name</label>
              <input required name="name" value={formData.name} onChange={handleChange} placeholder="e.g. MTS / Postman Study Guide" className="form-input" />
            </div>

            <div className="form-group">
              <label className="form-label">Category</label>
              <select required name="category" value={formData.category} onChange={handleChange} className="form-select">
                <option value="books">Books</option>
                <option value="materials">Materials</option>
                <option value="bundles">Bundles</option>
              </select>
            </div>

            <div className="form-group">
              <label className="form-label">Image URL / Path</label>
              <input required name="image" value={formData.image} onChange={handleChange} placeholder="e.g. /images/products/mts.jpg" className="form-input" />
            </div>

            <div className="form-group sm:col-span-2">
              <label className="form-label">Detailed Description</label>
              <textarea required name="description" value={formData.description} onChange={handleChange} placeholder="Write a summary details of the book edition, content coverage, etc." className="form-input" rows={4} />
            </div>
          </div>
        </div>

        {/* Section 2: Pricing & Inventory */}
        <div className="admin-form-section">
          <h3 className="admin-form-section__title">Pricing & Stock Level</h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
            <div className="form-group">
              <label className="form-label">Base Price (₹)</label>
              <input required type="number" step="0.01" name="price" value={formData.price} onChange={handleChange} placeholder="500" className="form-input" />
            </div>

            <div className="form-group">
              <label className="form-label">Initial Inventory</label>
              <input required type="number" name="stock" value={formData.stock} onChange={handleChange} className="form-input" />
            </div>

            <div className="form-group">
              <label className="form-label">Books Included Count</label>
              <input required type="number" name="booksIncluded" value={formData.booksIncluded} onChange={handleChange} className="form-input" />
            </div>
          </div>
        </div>

        {/* Section 3: Marketing Labels */}
        <div className="admin-form-section">
          <h3 className="admin-form-section__title">Marketing & Extras</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            <div className="form-group">
              <label className="form-label">Bundle Subtitle (Optional)</label>
              <input name="bundleTitle" value={formData.bundleTitle} onChange={handleChange} placeholder="e.g. Pack of 3 books" className="form-input" />
            </div>

            <div className="form-group">
              <label className="form-label">Promo Tag / Badge (Optional)</label>
              <input name="badge" value={formData.badge} onChange={handleChange} placeholder="e.g. Best Seller" className="form-input" />
            </div>
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex flex-col-reverse sm:flex-row justify-end gap-3 pt-4 border-t border-(--color-border)">
          <Link href="/admin/products" className="btn btn-secondary w-full sm:w-auto text-center justify-center">
            Cancel
          </Link>
          <button type="submit" disabled={loading} className="btn btn-primary w-full sm:w-auto justify-center">
            {loading ? 'Saving...' : 'Add Product'}
          </button>
        </div>
      </form>
    </div>
  );
}
